spring.application.name=todoapp-jpa-jdbc

#;INIT=CREATE SCHEMA IF NOT EXISTS my_schema\\;SET SCHEMA my_schema
#;DATABASE_TO_UPPER=false
#;MODE=PostgreSQL
spring.datasource.url=jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_UPPER=false;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.data.jdbc.dialect=postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/xyp
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=xyp
#spring.datasource.password=Xyp54250
#spring.data.jdbc.dialect=postgresql

spring.sql.init.schema-locations=classpath:/db/init/schema.sql
spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core=TRACE
logging.level.org.flywaydb.core.internal.database.DefaultParser=DEBUG
logging.level.org.springframework.boot.sql.init=DEBUG
